### ISSUE TITLE
Not working with node 6.7.0

### ISSUE THREAD

**Issue by Ciboulette** [gothinkster/react-redux-realworld-example-app#25]
Hey thanks for the beautiful work you do. I hope the tutorial will be out soon.

Is it normal with node 6.7.0 that when i run npm install, webpack is launched and I have ERROR in Cannot find module 'babel-core' . I can't launch the project.

Thanks

**Comment by EricSimons** [comment]
Thanks for the kind words :)

We need to update the dependencies, but if you npm install `babel-core` that should do the trick. We're currently switching the app over to `create-react-app` (not quite done yet but should be soon), so this shouldn't be an issue at all in the future!

**Comment by EricSimons** [comment]
This is solved with #24 -- `git pull` and `npm install` to get it running on an existing codebase!
